// База данных всех карт
const RAW_CARDS = {
  // Fire Set (subset extracted; extend as needed)
  FIRE_FLAME_MAGUS: {
    cardNumber: 1,
    race: 'Human',
    affiliation: 'Church of Parmus',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_FLAME_MAGUS', name: 'Flame Magus', type: 'UNIT', cost: 1, activation: 1,
    element: 'FIRE', atk: 1, hp: 1,
    attackType: 'MAGIC', // магическая атака
    attacks: [ { dir: 'N', ranges: [1, 2, 3], mode: 'ANY' } ], // стреляет вперёд на 1-3 клетки
    blindspots: ['N','E','S','W'],
    desc: 'Magic Attack: target any creature; no retaliation.'
  },
  FIRE_HELLFIRE_SPITTER: {
    cardNumber: 2,
    race: 'Bug',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_HELLFIRE_SPITTER', name: 'Hellfire Spitter', type: 'UNIT', cost: 1, activation: 1,
    element: 'FIRE', atk: 1, hp: 1,
    attackType: 'STANDARD', firstStrike: true,
    chooseDir: true, // выбирает одно направление атаки
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'S', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: [],
    desc: 'Quickness: always strikes first.'
  },
  FIRE_FREEDONIAN_WANDERER: {
    cardNumber: 3,
    race: 'Elemental',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_FREEDONIAN_WANDERER', name: 'Freedonian Wanderer', type: 'UNIT', cost: 2, activation: 1,
    element: 'FIRE', atk: 1, hp: 2,
    attackType: 'STANDARD', pierce: true,
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    manaOnSummon: {
      trigger: 'ALLY',
      sourceFieldNotElement: 'FIRE',
      excludeSelfSummon: true,
      log: 'Фридонийский Странник приносит {amount} маны.',
    },
    desc: 'While Freedonian Wanderer is on a non‑Fire field, you gain 1 mana each time you summon an allied creature.'
  },
  FIRE_PARTMOLE_FLAME_LIZARD: {
    cardNumber: 4,
    race: 'Lizard',
    affiliation: 'Dhees Empire',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_PARTMOLE_FLAME_LIZARD', name: 'Partmole Flame Lizard', type: 'UNIT', cost: 2, activation: 2,
    element: 'FIRE', atk: 2, hp: 2,
    attackType: 'STANDARD', firstStrike: true, activationReduction: 1,
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    desc: 'Quickness. The activation cost to attack is 1 less than listed.'
  },
  FIRE_GREAT_MINOS: {
    cardNumber: 6,
    race: 'Titan',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_GREAT_MINOS', name: 'Great Minos of Sciondar', type: 'UNIT', cost: 3, activation: 2,
    element: 'FIRE', atk: 2, hp: 1,
    attackType: 'STANDARD', pierce: true,
    // бьёт сразу по двум клеткам впереди, игнорируя преграды и задевая союзников
    attacks: [ { dir: 'N', ranges: [1, 2] } ],
    blindspots: ['S'], perfectDodge: true, activationReduction: 1, diesOffElement: 'FIRE',
    friendlyFire: true, pierce: true,
    desc: 'Perfect Dodge. The activation cost to attack is 1 less. Destroy Great Minos if he is on a non‑Fire field.'
  },
  FIRE_FLAME_ASCETIC: {
    cardNumber: 7,
    race: 'Human',
    affiliation: 'Cult of Mourning',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_FLAME_ASCETIC', name: 'Flame Ascetic', type: 'UNIT', cost: 3, activation: 3,
    element: 'FIRE', atk: 2, hp: 3,
    attackType: 'STANDARD', activationReduction: 2,
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'], randomPlus2: true,
    desc: 'Adds 2 to its Attack half the time. The activation cost to attack is 2 less than listed.'
  },
  FIRE_TRICEPTAUR_BEHEMOTH: {
    cardNumber: 11,
    race: 'Beast',
    affiliation: 'Dhees Empire',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_TRICEPTAUR_BEHEMOTH', name: 'Triceptaur Behemoth', type: 'UNIT', cost: 5, activation: 5,
    element: 'FIRE', atk: 5, hp: 4,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: ['S'], penaltyByTargets: { '2': -2, '3': -4 },
    friendlyFire: true,
    desc: 'When Triceptaur Behemoth attacks 2 creatures, subtract 2 from its Attack; when attacking 3 creatures, subtract 4.'
  },
  FIRE_PURSUER_OF_SAINT_DHEES: {
    cardNumber: 12,
    race: 'Demon',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_PURSUER_OF_SAINT_DHEES', name: 'Pursuer of Saint Dhees', type: 'UNIT', cost: 6, activation: 6,
    element: 'FIRE', atk: 5, hp: 4,
    attackType: 'STANDARD', activationReduction: 5,
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'], dynamicAtk: 'OTHERS_ON_BOARD',
    desc: 'Attack = 5 plus the number of other creatures on the board. The activation cost to attack is 5 less than listed.'
  },

  FIRE_PARTMOLE_FLAME_GUARD: {
    cardNumber: 8,
    race: 'Demon',
    affiliation: 'Dhees Empire',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_PARTMOLE_FLAME_GUARD', name: 'Partmole Flame Guard', type: 'UNIT', cost: 3, activation: 2,
    element: 'FIRE', atk: 1, hp: 3,
    attackType: 'STANDARD',
    // пробивает первую цель и бьёт следующую за ней
    attacks: [ { dir: 'N', ranges: [1,2] } ],
    pierce: true,
    blindspots: ['S'],
    plusAtkIfTargetOnElement: { element: 'WATER', amount: 2 },
    desc: 'Adds 2 to its Attack if at least one target creature is on a water field.'
  },

  FIRE_LESSER_GRANVENOA: {
    cardNumber: 9,
    race: 'Base',
    affiliation: 'Cai-Shae',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_LESSER_GRANVENOA', name: 'Lesser Granvenoa', type: 'UNIT', cost: 4, activation: 2,
    element: 'FIRE', atk: 2, hp: 4,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'S', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: [], fortress: true, diesOnElement: 'WATER', fieldquakeLock: { type: 'ADJACENT' },
    desc: 'Fortress. Adjacent fields cannot be field‑quaked or exchanged. Destroy Lesser Granvenoa if it is on a Water field.'
  },

  FIRE_PARTMOLE_FIRE_ORACLE: {
    cardNumber: 10,
    race: 'Demon',
    affiliation: 'Church of Parmus',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_PARTMOLE_FIRE_ORACLE', name: 'Partmole Fire Oracle', type: 'UNIT', cost: 4, activation: 2,
    element: 'FIRE', atk: 2, hp: 3,
    attackType: 'MAGIC',
    attacks: [ { dir: 'N', ranges: [1,2,3], mode: 'ANY' } ],
    blindspots: ['N','E','S','W'], onDeathAddHPAll: 1,
    desc: 'Magic Attack. If destroyed, all allied creatures on board gain 1 HP.'
  },

  FIRE_INFERNAL_SCIONDAR_DRAGON: {
    cardNumber: 13,
    race: 'Dragon',
    affiliation: 'Dhees Empire',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_INFERNAL_SCIONDAR_DRAGON', name: 'Infernal Sciondar Dragon', type: 'UNIT', cost: 7, activation: 4,
    element: 'FIRE', atk: 5, hp: 8,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1,2] } ],
    blindspots: [], dynamicAtk: 'FIRE_CREATURES', activationReductionOnElement: { element: 'FIRE', reduction: 3 },
    desc: 'Attack = 5 plus the number of other Fire creatures on the board. While on a Fire field, its activation cost to attack is 3 less than listed.'
  },

  FIRE_DIDI_THE_ENLIGHTENED: {
    cardNumber: 14,
    race: 'Hero',
    affiliation: 'Cai-Shae',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FIRE_DIDI_THE_ENLIGHTENED', name: 'Didi the Enlightened', type: 'UNIT', cost: 3, activation: 2,
    element: 'FIRE', atk: 2, hp: 4,
    attackType: 'STANDARD', firstStrike: true, doubleAttack: true,
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'], plusAtkIfTargetOnElement: { element: 'FIRE', amount: 1 }, fieldquakeLock: { type: 'ELEMENT', element: 'FIRE' },
    desc: 'Quickness. Attacks the same target twice (counterattack after second attack). Adds 1 to his Attack if the target creature is on a Fire field. While Didi is on the board, no Fire field can be field‑quaked or exchanged.'
  },

  FIRE_WARDEN_HILDA: {
    cardNumber: 15,
    race: 'Betrayer',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FIRE_WARDEN_HILDA', name: 'Warden Hilda', type: 'UNIT', cost: 3, activation: 2,
    element: 'FIRE', atk: 2, hp: 4,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2] } ],
    blindspots: ['S'],
    plusAtkVsElement: { element: 'FIRE', amount: 1 },
    gainPossessionEnemiesOnElement: { element: 'FIRE', requireDifferentField: true },
    desc: 'Adds 1 to her Attack if the target is a Fire creature. If summoned on a non‑Fire field, you gain possession of any enemies on a Fire field.'
  },

  FIRE_CRUCIBLE_KING_DIOS_IV: {
    cardNumber: 16,
    race: 'Noble',
    affiliation: 'Dhees Empire',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FIRE_CRUCIBLE_KING_DIOS_IV', name: 'Crucible King Dios IV', type: 'UNIT', cost: 6, activation: 4,
    element: 'FIRE', atk: 3, hp: 6,
    attackType: 'STANDARD', doubleAttack: true,
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    mustUseMagicOnElement: 'FIRE', magicAttackArea: 'CROSS', dynamicMagicAtk: 'FIRE_FIELDS',
    attackSchemes: [
      { key: 'BASE', label: 'Base', attackType: 'STANDARD', attacks: [ { dir: 'N', ranges: [1] } ] },
      { key: 'ALT', label: 'Alt', attackType: 'MAGIC', magicArea: 'CROSS' },
    ],
    desc: 'Attacks the same target twice (counterattack after second attack). While on a Fire field he must use his Magic Attack, which affects the target and all adjacent enemies. The Attack value is equal to the number of Fire fields.'
  },

  FIRE_RED_CUBIC: {
    cardNumber: 18,
    race: 'Egg',
    affiliation: 'Unknown',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_RED_CUBIC', name: 'Red Cubic', type: 'UNIT', cost: 1, activation: 1,
    element: 'FIRE', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['E', 'S', 'W'],
    unitActions: [
      { key: 'SACRIFICE_TRANSFORM', element: 'FIRE', label: 'Sacrifice', requireNonCubic: true, allowLockedTargets: true },
    ],
    desc: 'Sacrifice Red Cubic to summon a non‑cubic Fire creature in its place (facing any direction) without paying the summoning cost. The summoned creature cannot attack on this turn.'
  },

  FIRE_SCIONDAR_FIRE_GOD: {
    cardNumber: 17,
    race: 'God',
    affiliation: 'Unknown',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FIRE_SCIONDAR_FIRE_GOD', name: 'Sciondar Fire God', type: 'UNIT', cost: 9, activation: 5,
    element: 'FIRE', atk: 3, hp: 9,
    attackType: 'MAGIC',
    attacks: [], blindspots: [],
    incarnation: true,
    targetAllNonElement: 'FIRE',
    diesOnElement: 'BIOLITH',
    desc: 'Incarnation. Its Magic Attack targets all enemies on non-Fire fields. Destroy Sciondar Fire God if he is on a Biolith field.'
  },

  WATER_GODDESS_TRITONA: {
    cardNumber: 35,
    race: 'God',
    affiliation: 'Unknown',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'WATER_GODDESS_TRITONA', name: 'Goddess Tritona', type: 'UNIT', cost: 9, activation: 5,
    element: 'WATER', atk: 3, hp: 9,
    attackType: 'MAGIC',
    attacks: [], blindspots: [],
    incarnation: true,
    targetAllNonElement: 'WATER',
    diesOnElement: 'BIOLITH',
    desc: 'Incarnation. Goddess Tritona’s Magic Attack targets all enemies on non-Water fields. Destroy Goddess Tritona if she is on a Biolith field.'
  },

  WATER_CLOUD_RUNNER: {
    cardNumber: 25,
    race: 'Weapon',
    affiliation: 'Siam Pirates',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_CLOUD_RUNNER', name: 'Cloud Runner', type: 'UNIT', cost: 3, activation: 2,
    element: 'WATER', atk: 1, hp: 2,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'E', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true },
    ],
    dodge: { chance: 0.5, attempts: 1 },
    drawOnSummonByElementFields: { element: 'WATER', includeSelf: true, includeCenter: true },
    desc: 'Dodge attempt. When Cloud Runner is summoned, draw cards equal to the number of Water fields.'
  },

  WATER_TRITONAN_ICE_GUARD: {
    cardNumber: 20,
    race: 'Elemental',
    affiliation: 'Tritonan Queendom',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_TRITONAN_ICE_GUARD', name: 'Tritonan Ice Guard', type: 'UNIT', cost: 1, activation: 1,
    element: 'WATER', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    drawOnSummonIfFieldNotElement: 'WATER',
    desc: 'When Tritonan Ice Guard is summoned to a non-Water field, draw a card.'
  },

  WATER_MONK_ELDER_OF_OKUNADA: {
    cardNumber: 19,
    race: 'Merfolk',
    affiliation: 'Okunada Monastery',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_MONK_ELDER_OF_OKUNADA', name: 'Monk Elder of Okunada', type: 'UNIT', cost: 1, activation: 1,
    element: 'WATER', atk: 0, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    grantDodgeAdjacentAllies: 1,
    desc: 'All allied creatures on adjacent fields gain one Dodge attempt.'
  },

  WATER_DRAGON_OF_VOICE_SEA: {
    cardNumber: 31,
    race: 'Dragon',
    affiliation: 'Tritonan Queendom',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_DRAGON_OF_VOICE_SEA', name: 'Dragon of Voice Sea', type: 'UNIT', cost: 7, activation: 4,
    element: 'WATER', atk: 5, hp: 8,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    dynamicAtk: 'WATER_CREATURES',
    drawOnAllySummonAdjacent: { amount: 1, sourceOnElement: 'WATER' },
    desc: 'Dragon of Voice Sea\'s Attack is equal to 5 plus the number of other Water creatures on the board. While Dragon of Voice Sea is on a Water field, if you summon a creature to an adjacent field, draw a card.'
  },

  WATER_DON_OF_VENOA: {
    cardNumber: 30,
    race: 'Titan',
    affiliation: 'Corsez Family',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_DON_OF_VENOA', name: 'Don of Venoa', type: 'UNIT', cost: 5, activation: 3,
    element: 'WATER', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attackSchemes: [
      {
        key: 'BASE',
        label: 'Cleave',
        attacks: [
          { dir: 'N', ranges: [1], group: 'FRONT_BACK' },
          { dir: 'S', ranges: [1], group: 'FRONT_BACK' },
        ],
      },
      {
        key: 'WATER_SWIRL',
        label: 'Whirlpool',
        attacks: [
          { dir: 'N', ranges: [1], group: 'SWIRL' },
          { dir: 'S', ranges: [1], group: 'SWIRL' },
          { dir: 'E', ranges: [1], group: 'SWIRL' },
          { dir: 'W', ranges: [1], group: 'SWIRL' },
        ],
      },
    ],
    defaultAttackScheme: 'BASE',
    mustUseSchemeOnElement: [ { element: 'WATER', scheme: 'WATER_SWIRL' } ],
    dodge: { chance: 0.5, attempts: 1 },
    gainDodgeFromAdjacentEnemies: { attemptsPerEnemy: 1 },
    grantDodgeAdjacentAllies: 1,
    desc: 'Dodge attempt. Gains one Dodge attempt for each adjacent enemy. Adjacent allied creatures gain one Dodge attempt. While on a Water field he strikes all adjacent cells.'
  },

  WATER_MERCENARY_SAVIOR_LATOO: {
    cardNumber: 32,
    race: 'Hero',
    affiliation: 'Tritonan Queendom',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'WATER_MERCENARY_SAVIOR_LATOO', name: 'Mercenary Savior Latoo', type: 'UNIT', cost: 3, activation: 2,
    element: 'WATER', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], group: 'LINE' } ],
    plusAtkIfTargetOnElement: { element: 'WATER', amount: 1 },
    auraGrantDodgeOnElement: { element: 'WATER', attempts: 1, includeSelf: false },
    dodge: { chance: 0.5, attempts: 1 },
    desc: 'Dodge attempt. Adds 1 to his Attack if at least one target is on a Water field. While Latoo is on the board, allied creatures on Water fields gain one Dodge attempt.'
  },

  WATER_TRITONAN_HARPOONSMAN: {
    cardNumber: 21,
    race: 'Merfolk',
    affiliation: 'Tritonan Queendom',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_TRITONAN_HARPOONSMAN', name: 'Tritonan Harpoonsman', type: 'UNIT', cost: 2, activation: 1,
    element: 'WATER', atk: 1, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], group: 'LINE' } ],
    gainDodgeOnElement: { element: 'WATER', attempts: 1 },
    desc: 'While on a Water field Tritonan Harpoonsman gains Dodge attempt.'
  },

  WATER_ALUHJA_PRIESTESS: {
    cardNumber: 22,
    race: 'Human',
    affiliation: 'Church of Parmus',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_ALUHJA_PRIESTESS', name: 'Aluhja Priestess', type: 'UNIT', cost: 2, activation: 1,
    element: 'WATER', atk: 1, hp: 1,
    attackType: 'MAGIC',
    attacks: [ { dir: 'N', ranges: [1, 2, 3], mode: 'ANY' } ],
    blindspots: ['N', 'E', 'S', 'W'],
    gainDodgeOnElement: { element: 'WATER', attempts: 1 },
    desc: 'Magic Attack. While on a Water field, Aluhja Priestess gains Dodge attempt.'
  },

  WATER_MOVING_ISLE_OF_KADENA: {
    cardNumber: 29,
    race: 'Beast',
    affiliation: 'Tritonan Queendom',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_MOVING_ISLE_OF_KADENA', name: 'Moving Isle of Kadena', type: 'UNIT', cost: 4, activation: 2,
    element: 'WATER', atk: 1, hp: 4,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'E', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'S', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1], ignoreAlliedBlocking: true },
    ],
    blindspots: [], fortress: true, ignoreAlliedBlocking: true,
    diesOnElement: 'FIRE',
    manaSteal: {
      onSummon: {
        amount: { type: 'FIELD_COUNT', element: 'WATER' },
        forbidFieldElement: 'WATER',
      },
    },
    desc: 'Fortress. If Moving Isle of Kadena is summoned to a non-Water field, steal mana from your opponent equal to the number of Water fields. Destroy Moving Isle of Kadena if it is on a Fire field.'
  },

  WATER_QUEENS_SERVANT: {
    cardNumber: 28,
    race: 'Elemental',
    affiliation: 'Tritonan Queendom',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_QUEENS_SERVANT', name: "Queen's Servant", type: 'UNIT', cost: 4, activation: 2,
    element: 'WATER', atk: 1, hp: 1,
    attackType: 'MAGIC',
    attacks: [ { dir: 'N', ranges: [1, 2, 3], mode: 'ANY' } ],
    blindspots: ['S'], perfectDodge: true, ignoreAlliedBlocking: true,
    manaSteal: {
      onDeath: { amount: 1 },
    },
    desc: "Magic Attack. Perfect Dodge. If Queen's Servant is destroyed, steal 1 mana from your opponent."
  },

  WATER_DANCING_TEMPTRESS: {
    cardNumber: 26,
    race: 'Undead',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_DANCING_TEMPTRESS', name: 'Dancing Temptress', type: 'UNIT', cost: 3, activation: 2,
    element: 'NEUTRAL', atk: 1, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    deathPullFrontToSelf: true,
    manaSteal: {
      onDeath: { amount: 1, from: 'FRONT_OWNER' },
    },
    desc: 'If Dancing Temptress is destroyed, you steal 1 mana from the owner of the creature on the field in front of her. If Dancing Temptress is destroyed, the creature on the field in front of her is moved to the field she was previously on.'
  },

  EARTH_ARELAI_THE_PROTECTOR: {
    cardNumber: 50,
    race: 'Hero',
    affiliation: 'Saint Val Devotee',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'EARTH_ARELAI_THE_PROTECTOR', name: 'Arelai the Protector', type: 'UNIT', cost: 3, activation: 2,
    element: 'EARTH', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1], group: 'FRONT_BACK', ignoreAlliedBlocking: true },
      { dir: 'S', ranges: [1], group: 'FRONT_BACK', ignoreAlliedBlocking: true },
    ],
    blindspots: [],
    ignoreAlliedBlocking: true,
    protectionEqualsFieldCount: 'EARTH',
    plusAtkIfTargetOnElement: { element: 'EARTH', amount: 1 },
    auraModifiers: [
      { stat: 'PROTECTION', amount: 1, scope: 'BOARD', target: 'ALLY', targetOnElement: 'EARTH', excludeSelf: true },
    ],
    desc: 'Arelai gains Protection equal to the number of Earth fields.\nArelai adds +1 to his Attack if at least one target creature is on an Earth field.\nAll other allied creatures on Earth fields gain +1 Protection.'
  },

  EARTH_NOVOGUS_GOLEM: {
    cardNumber: 46,
    race: 'Beast',
    affiliation: 'Novogus Dynasty',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_NOVOGUS_GOLEM', name: 'Novogus Golem', type: 'UNIT', cost: 4, activation: 2,
    element: 'EARTH', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    protectionEqualsEmptyFields: true,
    desc: 'Novogus Golem gains Protection equal to the number of empty fields.'
  },
  EARTH_NOVOGUS_CATAPULT: {
    cardNumber: 43,
    race: 'Weapon',
    affiliation: 'Novogus Dynasty',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_NOVOGUS_CATAPULT', name: 'Novogus Catapult', type: 'UNIT', cost: 3, activation: 1,
    element: 'EARTH', atk: 2, hp: 4,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [2], ignoreBlocking: true, ignoreAlliedBlocking: true } ],
    blindspots: ['S'], ignoreAlliedBlocking: true,
    gainManaOnDeath: { mode: 'COUNT_FIELDS_OF_ELEMENT', element: 'EARTH' },
    desc: 'If Novogus Catapult is destroyed, you gain mana equal to the number of Earth fields.'
  },
  EARTH_SKELETON_SOLDIER: {
    cardNumber: 40,
    race: 'Undead',
    affiliation: 'Novogus Dynasty',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_SKELETON_SOLDIER', name: 'Skeleton Soldier', type: 'UNIT', cost: 2, activation: 1,
    element: 'EARTH', atk: 1, hp: 2,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1], group: 'FRONT_LEFT', ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1], group: 'FRONT_LEFT', ignoreAlliedBlocking: true }
    ],
    blindspots: ['S', 'E'], ignoreAlliedBlocking: true,
    gainManaOnDeath: 1,
    desc: 'If Skeleton Soldier is destroyed, you gain 1 additional mana.'
  },
  EARTH_UNDEAD_DRAGON: {
    cardNumber: 49,
    race: 'Dragon',
    affiliation: 'Novogus Dynasty',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_UNDEAD_DRAGON', name: 'Undead Dragon', type: 'UNIT', cost: 7, activation: 4,
    element: 'EARTH', atk: 5, hp: 8,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true } ],
    blindspots: ['S'], ignoreAlliedBlocking: true,
    dynamicAtk: 'EARTH_CREATURES',
    allyDeathGainMana: { amount: 1, requireFieldElement: 'EARTH', adjacency: 'ORTHOGONAL' },
    desc: "Undead Dragon's Attack is equal to 5 plus the number of other Earth creatures on the board. While Undead Dragon is on an Earth field, gain 1 additional mana whenever an adjacent allied creature is destroyed."
  },

  EARTH_SE_HOLLYN_FORTRESS: {
    cardNumber: 45,
    race: 'Base',
    affiliation: 'Val na Vos',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_SE_HOLLYN_FORTRESS', name: 'Se Hollyn Fortress', type: 'UNIT', cost: 4, activation: 2,
    element: 'EARTH', atk: 1, hp: 4,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'E', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'S', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1], ignoreAlliedBlocking: true }
    ],
    blindspots: [],
    ignoreAlliedBlocking: true,
    fortress: true,
    auraModifiers: [
      { stat: 'PROTECTION', amount: 2, scope: 'ADJACENT', target: 'ALLY', excludeSelf: true },
    ],
    diesOnElement: 'FOREST',
    desc: 'Fortress.\nAllied creatures on adjacent fields gain +2 Protection.\nDestroy Se Hollyn Fortress if it is on a Wood field.'
  },

  EARTH_GIANT_AXE_DWARF: {
    cardNumber: 41,
    race: 'Dwarf',
    affiliation: 'Hammer Valley',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_GIANT_AXE_DWARF', name: 'Giant Axe Dwarf', type: 'UNIT', cost: 2, activation: 1,
    element: 'EARTH', atk: 1, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    dynamicAtkAlliedTemplates: { templates: ['EARTH_STONE_WING_DWARF', 'Stone Wing Dwarf'], amountPer: 1, includeSelf: false },
    desc: 'Giant Axe Dwarf adds 1 to his Attack for every allied Stone Wing Dwarf on the board.'
  },

  EARTH_STONE_WING_DWARF: {
    cardNumber: 39,
    race: 'Dwarf',
    affiliation: 'Hammer Valley',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_STONE_WING_DWARF', name: 'Stone Wing Dwarf', type: 'UNIT', cost: 1, activation: 1,
    element: 'EARTH', atk: 1, hp: 1,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'E', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'S', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1], ignoreAlliedBlocking: true }
    ],
    blindspots: [],
    ignoreAlliedBlocking: true,
    protectionEqualsAlliedTemplates: ['EARTH_GIANT_AXE_DWARF', 'Giant Axe Dwarf'],
    desc: 'Stone Wing Dwarf gains Protection equal to the number of allied Giant Axe Dwarves on the board.'
  },

  EARTH_BLACK_HOOD_DWARF_VULITRA: {
    cardNumber: 51,
    race: 'Betrayer',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'EARTH_BLACK_HOOD_DWARF_VULITRA', name: 'Black Hood Dwarf Vulitra', type: 'UNIT', cost: 3, activation: 2,
    element: 'EARTH', atk: 2, hp: 4,
    attackType: 'STANDARD', friendlyFire: true,
    attacks: [ { dir: 'N', ranges: [1, 2], ignoreAlliedBlocking: true } ],
    blindspots: ['S'], ignoreAlliedBlocking: true, pierce: true,
    retaliationRangeCap: 1,
    plusAtkVsElement: { element: 'EARTH', amount: 1 },
    deathDiscardOnNonElement: { element: 'EARTH', count: { type: 'FIELD_COUNT', element: 'EARTH' } },
    desc: 'Vulitra adds 1 to his attack if at least one target creature is an earth creature. If Vulitra is destroyed on a non-Earth field, your opponent must discard cards equal to the number of Earth fields.'
  },

  EARTH_VERZAR_FOOT_SOLDIER: {
    cardNumber: 38,
    race: 'Human',
    affiliation: 'Val na Vos',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_VERZAR_FOOT_SOLDIER', name: 'Verzar Foot Soldier', type: 'UNIT', cost: 1, activation: 1,
    element: 'EARTH', atk: 1, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    dynamicAtkAlliedTemplates: { templates: ['EARTH_VERZAR_FOOT_SOLDIER', 'Verzar Foot Soldier'], amountPer: 1, includeSelf: false, minCount: 1, maxCount: 1 },
    desc: 'Verzar Foot Soldier adds 1 to his Attack if at least one other allied Verzar Foot Soldier is on the board.'
  },

  EARTH_VERZAR_CANINE: {
    cardNumber: 37,
    race: 'Beast',
    affiliation: 'Val na Vos',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_VERZAR_CANINE', name: 'Verzar Canine', type: 'UNIT', cost: 1, activation: 1,
    element: 'EARTH', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    auraModifiers: [
      { stat: 'PROTECTION', amount: 1, scope: 'ADJACENT', target: 'ALLY' },
    ],
    desc: 'Allied creatures on adjacent fields gain +1 Protection.'
  },

  BIOLITH_MORNING_STAR_WARRIOR: {
    cardNumber: 77,
    race: 'Mech',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_MORNING_STAR_WARRIOR', name: 'Morning Star Warrior', type: 'UNIT', cost: 4, activation: 2,
    element: 'BIOLITH', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    plusAtkIfTargetHpAtLeast: { threshold: 5, amount: 2 },
    protectionSources: [
      { type: 'ALLY_ELEMENT', element: 'BIOLITH', includeSelf: false },
    ],
    desc: 'Morning Star Warrior adds 2 to its Attack if the target creature has 5 or more HPs.\nMorning Star Warrior gains Protection equal to the number of allied Biolith creatures.'
  },
  BIOLITH_BIOLITH_STINGER: {
    cardNumber: 74,
    race: 'Bug',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_BIOLITH_STINGER', name: 'Biolith Stinger', type: 'UNIT', cost: 3, activation: 2,
    element: 'BIOLITH', atk: 0, hp: 1,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'S', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: [],
    dodge: { chance: 0.5, attempts: 1 },
    swapOnDamage: true,
    swapOnDamageAllowZero: true,
    desc: 'Dodge attempt. If Biolith Stinger damages (but does not destroy) a creature, it switches locations with that creature (which cannot counterattack).'
  },
  BIOLITH_IMPERIAL_BIOLITH_GUARD: {
    cardNumber: 75,
    race: 'Mech',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_IMPERIAL_BIOLITH_GUARD', name: 'Imperial Biolith Guard', type: 'UNIT', cost: 3, activation: 2,
    element: 'BIOLITH', atk: 2, hp: 4,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'E', ranges: [1], group: 'SIDE_SWEEP', ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1], group: 'SIDE_SWEEP', ignoreAlliedBlocking: true },
    ],
    blindspots: [],
    ignoreAlliedBlocking: true,
    manaOnSummon: {
      trigger: 'ALLY',
      summonFieldElement: 'BIOLITH',
      excludeSelfSummon: true,
      log: 'Imperial Biolith Guard генерирует {amount} ману за биолитовый призыв.',
    },
    desc: 'Gain 1 mana each time you summon a creature to a Biolith field.'
  },
  BIOLITH_WORMAK_HEIR: {
    cardNumber: 86,
    race: 'Betrayer',
    affiliation: 'Phantom',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'BIOLITH_WORMAK_HEIR', name: 'Wormak Heir to the Bioliths', type: 'UNIT', cost: 4, activation: 2,
    element: 'BIOLITH', atk: 2, hp: 4,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: [],
    ignoreAlliedBlocking: true,
    targetCountAttack: {
      match: { owner: 'ENEMY', element: 'BIOLITH' },
      count: { type: 'NON_ELEMENT', element: 'BIOLITH' },
      baseValue: 2,
      amountPer: 1,
      log: 'Wormak Heir to the Bioliths: атака против биолитов установлена на {targetValue} (небиолитовых существ: {count}).',
    },
    manaOnSummon: {
      trigger: 'ENEMY',
      log: 'Wormak Heir to the Bioliths получает {amount} ману за призыв врага.',
    },
    desc: "If the target is an enemy Biolith, Wormak's Attack is equal to 2 plus the number of non-Biolith creatures on the board.\nGain 1 mana each time an enemy is summoned."
  },
  BIOLITH_TINO_SON_OF_SCION: {
    cardNumber: 85,
    race: 'Hero',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'BIOLITH_TINO_SON_OF_SCION', name: 'Tino, Son of Scion', type: 'UNIT', cost: 4, activation: 3,
    element: 'BIOLITH', atk: 3, hp: 4,
    attackType: 'MAGIC',
    attacks: [],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    magicTargetsSameElement: true,
    dynamicAtkAlliedElementOnField: {
      element: 'BIOLITH',
      baseValue: 1,
      amountPer: 1,
      requireFieldElement: 'BIOLITH',
      includeSelf: false,
    },
    manaOnSummon: {
      trigger: 'ALLY',
      excludeSelfSummon: true,
      log: 'Tino, Son of Scion приносит {amount} ману.',
    },
    desc: "Tino's Magic Attack targets all enemies of the same element as the target.\nWhile Tino is on a Biolith field, his Attack is equal to 1 plus the number of other allied Biolith creatures.\nGain 1 mana each time you summon a creature."
  },
  BIOLITH_GUARDIAN_WATCHTOWER: {
    cardNumber: 88,
    race: 'Ancient',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'BIOLITH_GUARDIAN_WATCHTOWER', name: 'Guardian Watchtower', type: 'UNIT', cost: 6, activation: 3,
    element: 'BIOLITH', atk: 1, hp: 10,
    attackType: 'MAGIC',
    attacks: [],
    blindspots: [],
    ignoreAlliedBlocking: true,
    magicTargetsSameElement: true,
    rotateTargetOnDamage: { mode: 'OPPOSITE' },
    resolutionManaOnAllyPresence: {
      requireTplIds: ['BIOLITH_SCION_BIOLITH_LORD'],
      amountPer: 1,
      includeSelf: false,
      phase: 'TURN_START',
      log: 'Guardian Watchtower приносит {amount} маны (союзных существ: {allies}).',
    },
    desc: "Guardian Watchtower's Magic Attack targets all enemies of the same element as the target.\nWhen Guardian Watchtower damages (but does not destroy) a creature, that creature is rotated 180° and cannot counterattack.\nWhile an allied Scion is on the board, gain mana equal to the number of allied creatures on the board during your Resolution Phase."
  },

  EARTH_NOVOGUS_GRAVEKEEPER: {
    cardNumber: 53,
    race: 'God',
    affiliation: 'Unknown',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'EARTH_NOVOGUS_GRAVEKEEPER', name: 'Novogus Gravekeeper', type: 'UNIT', cost: 9, activation: 5,
    element: 'EARTH', atk: 3, hp: 9,
    attackType: 'MAGIC',
    attacks: [], blindspots: [],
    incarnation: true,
    targetAllNonElement: 'EARTH',
    diesOnElement: 'BIOLITH',
    desc: 'Incarnation. Novogus Gravekeeper’s Magic Attack targets all enemies on non-Earth fields. Destroy Novogus Gravekeeper if it is on a Biolith field.'
  },

  FOREST_EXALTED_ELVEN_DEITY: {
    cardNumber: 71,
    race: 'God',
    affiliation: 'Unknown',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FOREST_EXALTED_ELVEN_DEITY', name: 'Exalted Elven Deity', type: 'UNIT', cost: 9, activation: 5,
    element: 'FOREST', atk: 3, hp: 9,
    attackType: 'MAGIC',
    attacks: [], blindspots: [],
    incarnation: true,
    targetAllNonElement: 'FOREST',
    diesOnElement: 'BIOLITH',
    desc: 'Incarnation. Exalted Elven Deity’s Magic Attack targets all enemies on non-Wood fields. Destroy Exalted Elven Deity if it is on a Biolith field.'
  },

  BIOLITH_PHASEUS: {
    cardNumber: 89,
    race: 'God',
    affiliation: 'Unknown',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'BIOLITH_PHASEUS', name: 'Phaseus, Biolith God', type: 'UNIT', cost: 9, activation: 5,
    element: 'BIOLITH', atk: 3, hp: 9,
    attackType: 'MAGIC',
    attacks: [], blindspots: [],
    incarnation: true,
    targetAllEnemies: true,
    diesOffElement: 'BIOLITH',
    desc: 'Incarnation. Phaseus’s Magic Attack targets all enemies. Destroy Phaseus if he is on a non-Biolith field.'
  },

  BIOLITH_BEHEMOTH_GROUNDBREAKER: {
    cardNumber: 79,
    race: 'Weapon',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_BEHEMOTH_GROUNDBREAKER', name: 'Behemoth Groundbreaker', type: 'UNIT', cost: 4, activation: 3,
    element: 'BIOLITH', atk: 1, hp: 4,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    fieldquakeOnSummon: { pattern: 'ADJACENT' },
    desc: 'When Behemoth Groundbreaker is summoned, fieldquake all adjacent fields.'
  },
  EARTH_UNDEAD_KING_NOVOGUS: {
    cardNumber: 52,
    race: 'Noble',
    affiliation: 'Novogus Dynasty',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'EARTH_UNDEAD_KING_NOVOGUS', name: 'Undead King Novogus', type: 'UNIT', cost: 6, activation: 3,
    element: 'EARTH', atk: 2, hp: 6,
    attackType: 'MAGIC',
    attacks: [],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    fieldquakeOnDamage: { requireAttackerNotElement: 'EARTH', preventRetaliation: true },
    desc: "Magic Attack. If Undead King Novogus is on a non-Earth field and damages a creature, fieldquake the target creature's field. The target creature cannot counterattack."
  },
  BIOLITH_OUROBOROS_DRAGON: {
    cardNumber: 84,
    race: 'Dragon',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_CARD', amount: 1 },
    id: 'BIOLITH_OUROBOROS_DRAGON', name: 'Ouroboros Dragon', type: 'UNIT', cost: 7, activation: 4,
    element: 'BIOLITH', atk: 7, hp: 10,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    dynamicAtk: 'BIOLITH_CREATURES',
    fieldquakeLock: { type: 'ALL', onlyWhileOnElement: 'BIOLITH' },
    desc: "Ouroboros Dragon's Attack is equal to 7 plus the number of other Biolith creatures on the board. While Ouroboros Dragon is on a Biolith field, no field can be fieldquaked or exchanged."
  },

  // Ninja cycle
  FIRE_FIREFLY_NINJA: {
    cardNumber: 5,
    race: 'Human',
    affiliation: 'Yaksha',
    fieldLock: false,
    cardLimit: null,
    id: 'FIRE_FIREFLY_NINJA', name: 'Firefly Ninja', type: 'UNIT', cost: 3, activation: 2,
    element: 'FIRE', atk: 1, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    gainPerfectDodgeOnElement: 'FIRE',
    invisibilityAllies: ['EARTH_SPIDER_NINJA'],
    desc: 'While on a Fire field it gains Perfect Dodge. Gains Invisibility while at least one allied Spider Ninja is on the board.'
  },
  EARTH_SPIDER_NINJA: {
    cardNumber: 42,
    race: 'Human',
    affiliation: 'Yaksha',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_SPIDER_NINJA', name: 'Spider Ninja', type: 'UNIT', cost: 3, activation: 2,
    element: 'EARTH', atk: 2, hp: 1,
    attackType: 'MAGIC',
    attacks: [ { dir: 'N', ranges: [1, 2, 3], mode: 'ANY' } ],
    blindspots: ['S'],
    invisibilityAllies: ['WATER_WOLF_NINJA'],
    swapWithTargetOnElement: 'EARTH',
    desc: 'Magic attack. Gains Invisibility while at least one allied Wolf Ninja is on the board. If it damages a creature on an Earth field, it switches places with that creature (which cannot counterattack).'
  },
  EARTH_YELLOW_CUBIC: {
    cardNumber: 54,
    race: 'Egg',
    affiliation: 'Unknown',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_YELLOW_CUBIC', name: 'Yellow Cubic', type: 'UNIT', cost: 1, activation: 1,
    element: 'EARTH', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['E', 'S', 'W'],
    unitActions: [
      { key: 'SACRIFICE_TRANSFORM', element: 'EARTH', label: 'Sacrifice', requireNonCubic: true, allowLockedTargets: true },
    ],
    desc: 'Sacrifice Yellow Cubic to summon a non‑cubic Earth creature in its place (facing any direction) without paying the summoning cost. The summoned creature cannot attack on this turn.'
  },
  EARTH_DARK_YOKOZUNA_SEKIMARU: {
    cardNumber: 44,
    race: 'Titan',
    affiliation: 'Val na Vos',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_DARK_YOKOZUNA_SEKIMARU', name: 'Dark Yokozuna Sekimaru', type: 'UNIT', cost: 3, activation: 2,
    element: 'EARTH', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    pushTargetOnDamage: { distance: 1 },
    desc: 'If Dark Yokozuna Sekimaru attacks (but does not destroy) a creature, that creature is pushed back one field in the direction of the attack (provided the field is empty) and cannot counterattack.'
  },
  EARTH_VERZAR_ELEPHANT_BRIGADE: {
    cardNumber: 48,
    race: 'Elemental',
    affiliation: 'Val na Vos',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_VERZAR_ELEPHANT_BRIGADE', name: 'Verzar Elephant Brigade', type: 'UNIT', cost: 5, activation: 3,
    element: 'EARTH', atk: 2, hp: 5,
    attackType: 'STANDARD',
    attackSchemes: [
      { key: 'BASE', attacks: [ { dir: 'N', ranges: [1, 2], group: 'LINE', ignoreBlocking: true } ] },
      { key: 'ALT', attacks: [ { dir: 'N', ranges: [1] } ] },
    ],
    defaultAttackScheme: 'BASE',
    mustUseSchemeOnElement: [ { element: 'EARTH', scheme: 'ALT' } ],
    blindspots: ['S'],
    auraModifiers: [
      { stat: 'ATK', amount: 2, target: 'ALLY', scope: 'ADJACENT', sourceOnElement: 'EARTH' },
      { stat: 'ACTIVATION', amount: 1, target: 'ALLY', scope: 'ADJACENT', sourceOnElement: 'EARTH' },
    ],
    desc: 'Verzar Elephant Brigade must use its secondary attack while it is on an Earth field. While Verzar Elephant Brigade is on an Earth field, allied creatures on adjacent fields add 2 to their Attack and 1 to their Activation Cost.'
  },
  EARTH_DUNGEON_OF_TEN_TYRANTS: {
    cardNumber: 47,
    race: 'Base',
    affiliation: 'Val na Vos',
    fieldLock: false,
    cardLimit: null,
    id: 'EARTH_DUNGEON_OF_TEN_TYRANTS', name: 'Dungeon of Ten Tyrants', type: 'UNIT', cost: 4, activation: 2,
    element: 'EARTH', atk: 1, hp: 4,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'S', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: [],
    fortress: true,
    manaGainOnNonElement: 'EARTH',
    diesOnElement: 'FOREST',
    desc: 'Fortress: cannot attack unless counterattacking. While on a non‑Earth field, its summoner gains 1 mana during their resolution phase. Destroy if on a Forest field.'
  },
  WATER_WOLF_NINJA: {
    cardNumber: 24,
    race: 'Human',
    affiliation: 'Yaksha',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_WOLF_NINJA', name: 'Wolf Ninja', type: 'UNIT', cost: 3, activation: 2,
    element: 'WATER', atk: 1, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2] } ],
    blindspots: ['S'],
    invisibilityAllies: ['FOREST_SWALLOW_NINJA'],
    swapWithTargetOnElement: 'WATER',
    desc: 'Gains Invisibility while at least one allied Swallow Ninja is on the board. If Wolf Ninja damages a creature on a Water field, it switches places with that creature (which cannot counterattack).'
  },
  WATER_BLUE_CUBIC: {
    cardNumber: 36,
    race: 'Egg',
    affiliation: 'Unknown',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_BLUE_CUBIC', name: 'Blue Cubic', type: 'UNIT', cost: 1, activation: 1,
    element: 'WATER', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['E', 'S', 'W'],
    unitActions: [
      { key: 'SACRIFICE_TRANSFORM', element: 'WATER', label: 'Sacrifice', requireNonCubic: true, allowLockedTargets: true },
    ],
    desc: 'Sacrifice Blue Cubic to summon a non‑cubic Water creature in its place (facing any direction) without paying the summoning cost. The summoned creature cannot attack on this turn.'
  },
  WATER_SIAM_TRAITOR_OF_SEAS: {
    cardNumber: 33,
    race: 'Betrayer',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'WATER_SIAM_TRAITOR_OF_SEAS', name: 'Siam, Traitor of Seas', type: 'UNIT', cost: 3, activation: 2,
    element: 'WATER', atk: 2, hp: 4,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    doubleAttack: true,
    plusAtkVsElement: { element: 'WATER', amount: 1 },
    auraModifiers: [
      { stat: 'ATK', amount: -1, target: 'ENEMY', scope: 'BOARD', targetOnElement: 'WATER' },
    ],
    desc: 'Siam attacks the same target twice. The counterattack of target creature occurs after second attack. Siam adds 1 Attack if the target creature is a Water creature. All enemies on Water fields subtract 1 from their Attack.'
  },
  WATER_VENOAN_ASSASSIN: {
    cardNumber: 27,
    race: 'Human',
    affiliation: 'Corsez Family',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_VENOAN_ASSASSIN', name: 'Venoan Assassin', type: 'UNIT', cost: 3, activation: 2,
    element: 'WATER', atk: 2, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    backAttack: true,
    desc: 'Always attacks the back of its target.'
  },
  WATER_TENTACLES_OF_POSSESSION: {
    cardNumber: 23,
    race: 'Beast',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'WATER_TENTACLES_OF_POSSESSION', name: 'Tentacles of Possession', type: 'UNIT', cost: 2, activation: 1,
    element: 'WATER', atk: 0, hp: 2,
    attackType: 'STANDARD',
    attacks: [],
    blindspots: ['S'],
    possession: true,
    possessionEffects: [
      { pattern: 'FRONT', range: 1, id: 'TENTACLES_FRONT' },
    ],
    desc: 'Tentacles of Possession gain Possession of the enemy directly in front of it.'
  },
  WATER_IMPOSTER_QUEEN_ANFISA: {
    cardNumber: 34,
    race: 'Noble',
    affiliation: 'Tritonan Queendom',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'WATER_IMPOSTER_QUEEN_ANFISA', name: 'Imposter Queen Anfisa', type: 'UNIT', cost: 6, activation: 2,
    element: 'WATER', atk: 2, hp: 5,
    attackType: 'MAGIC',
    attacks: [],
    blindspots: ['N','E','S','W'],
    possession: true,
    possessionEffects: [
      { pattern: 'ADJACENT', requireSourceElement: 'WATER', id: 'ANFISA_WATER_AURA' },
    ],
    desc: 'Magic Attack. While on a Water field, Imposter Queen Anfisa gains Possession of all enemies on adjacent fields.'
  },
  FOREST_SWALLOW_NINJA: {
    cardNumber: 62,
    race: 'Human',
    affiliation: 'Yaksha',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_SWALLOW_NINJA', name: 'Swallow Ninja', type: 'UNIT', cost: 3, activation: 2,
    element: 'FOREST', atk: 1, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2] } ],
    blindspots: ['S'],
    friendlyFire: true,
    pierce: true,
    invisibilityAllies: ['FIRE_FIREFLY_NINJA'],
    rotateTargetOnDamage: true,
    desc: 'Gains Invisibility while at least one allied Firefly Ninja is on the board. When Swallow Ninja damages (but does not destroy) a creature, rotate that creature so its back faces Swallow Ninja. The target creature cannot counterattack.'
  },
  FOREST_JUNO_PRISONER_TRAP: {
    cardNumber: 65,
    race: 'Plant',
    affiliation: 'Black Forest',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_JUNO_PRISONER_TRAP', name: 'Juno Prisoner Trap', type: 'UNIT', cost: 4, activation: 2,
    element: 'FOREST', atk: 0, hp: 4,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'S', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: [],
    fortress: true,
    onEnemySummonAdjacentHealAllies: 1,
    diesOnElement: 'EARTH',
    desc: 'Fortress: cannot attack unless counterattacking. When an enemy creature is summoned adjacent to it, all other allied creatures gain 1 HP. Destroy if on an Earth field.'
  },
  FOREST_JUNO_TREE_HAUNT: {
    cardNumber: 63,
    race: 'Titan',
    affiliation: 'Northern Forces',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_JUNO_TREE_HAUNT', name: 'Juno Tree Haunt', type: 'UNIT', cost: 3, activation: 1,
    element: 'FOREST', atk: 2, hp: 1,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreBlocking: true },
    ],
    blindspots: ['S'],
    perfectDodge: true,
    diesOffNonElement: 'FOREST',
    desc: 'Perfect Dodge. Destroy if on a non-Forest field.'
  },
  FOREST_EDIN_THE_PERSECUTED: {
    cardNumber: 68,
    race: 'Hero',
    affiliation: 'Northern Forces',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FOREST_EDIN_THE_PERSECUTED', name: 'Edin the Persecuted', type: 'UNIT', cost: 3, activation: 2,
    element: 'FOREST', atk: 2, hp: 3,
    attackType: 'MAGIC',
    attacks: [],
    blindspots: ['S'],
    plus1IfTargetOnElement: 'FOREST',
    grantInvisibilityToAlliesOnElement: 'FOREST',
    desc: '+1 Attack while attacking a creature on a Forest field. Allied creatures on Forest fields have Invisibility.'
  },
  FOREST_ELVEN_DEATH_DANCER: {
    cardNumber: 66,
    race: 'Elf',
    affiliation: 'Black Forest',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_ELVEN_DEATH_DANCER', name: 'Elven Death Dancer', type: 'UNIT', cost: 5, activation: 4,
    element: 'FOREST', atk: 1, hp: 3,
    attackType: 'MAGIC',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY' } ],
    blindspots: ['S'],
    swapOnDamage: true,
    enemyActivationTaxAdjacent: 3,
    desc: 'Magic Attack. If Elven Death Dancer damages (but does not destroy) a creature, she switches locations with that creature (which cannot counterattack). Enemies on adjacent fields add 3 to their Activation Cost.'
  },
  FOREST_ELVEN_RIDER: {
    cardNumber: 64,
    race: 'Elf',
    affiliation: 'Til Vorg Monarchy',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_ELVEN_RIDER', name: 'Elven Rider', type: 'UNIT', cost: 4, activation: 2,
    element: 'FOREST', atk: 2, hp: 4,
    attackType: 'STANDARD', friendlyFire: true,
    attacks: [ { dir: 'N', ranges: [1, 2], ignoreAlliedBlocking: true } ],
    blindspots: ['S'], ignoreAlliedBlocking: true, pierce: true,
    deathDiscardOnNonElement: { element: 'FOREST', count: { type: 'FIELD_COUNT', element: 'FOREST' } },
    desc: 'If Elven Rider is destroyed on a non-Wood field, your opponent must discard cards equal to the number of Wood fields.'
  },
  FOREST_INQUISITOR_KOOG: {
    cardNumber: 86,
    race: 'Betrayer',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FOREST_INQUISITOR_KOOG', name: 'Inquisitor Koog', type: 'UNIT', cost: 3, activation: 2,
    element: 'FOREST', atk: 2, hp: 4,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'E', ranges: [1], ignoreAlliedBlocking: true },
      { dir: 'W', ranges: [1], ignoreAlliedBlocking: true }
    ],
    blindspots: ['S'], ignoreAlliedBlocking: true,
    plusAtkVsElement: { element: 'FOREST', amount: 1 },
    gainManaOnDeath: 'ENEMIES',
    desc: 'Inquisitor Koog adds 1 to his attack if the target creature is a Wood creature. If Inquisitor Koog is destroyed, you gain additional mana equal to the number of enemies.'
  },
  FOREST_JUNO_FOREST_DRAGON: {
    cardNumber: 67,
    race: 'Dragon',
    affiliation: 'Til Vorg Monarchy',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_JUNO_FOREST_DRAGON', name: 'Juno Forest Dragon', type: 'UNIT', cost: 7, activation: 4,
    element: 'FOREST', atk: 5, hp: 8,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreBlocking: true } ],
    blindspots: ['S'],
    dynamicAtk: 'FOREST_CREATURES',
    auraModifiers: [
      { stat: 'ACTIVATION', amount: 2, target: 'ENEMY', scope: 'ADJACENT', sourceOnElement: 'FOREST' },
    ],
    desc: 'Juno Forest Dragon\'s Attack is equal to 5 plus the number of other Wood creatures on the board. While Juno Forest Dragon is on a Wood field, enemies on adjacent fields add 2 to their Activation Cost.'
  },
  FOREST_SLEEPTRAP: {
    cardNumber: 58,
    race: 'Plant',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_SLEEPTRAP', name: 'Sleeptrap', type: 'UNIT', cost: 2, activation: 1,
    element: 'FOREST', atk: 0, hp: 2,
    attackType: 'STANDARD',
    attacks: [],
    blindspots: ['N', 'E', 'S', 'W'],
    auraModifiers: [
      { stat: 'ACTIVATION', amount: 1, target: 'ENEMY', scope: 'ADJACENT' },
    ],
    desc: 'Enemies on adjacent fields add 1 to their Activation Cost.'
  },
  FOREST_GREEN_LYCANTHROPE: {
    cardNumber: 56,
    race: 'Anthromorph',
    affiliation: 'Til Vorg Monarchy',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_GREEN_LYCANTHROPE', name: 'Green Lycanthrope', type: 'UNIT', cost: 1, activation: 1,
    element: 'FOREST', atk: 0, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    randomSummonBuff: { chance: 0.5, hp: 3, atk: 2 },
    desc: 'When Green Lycanthrope is summoned, half the time add 3 to its HP and 2 to its Attack.'
  },

  FOREST_BEWITCHING_ELF_ARCHERESS: {
    cardNumber: 57,
    race: 'Elf',
    affiliation: 'Northern Forces',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_BEWITCHING_ELF_ARCHERESS', name: 'Bewitching Elf Archeress', type: 'UNIT', cost: 1, activation: 1,
    element: 'FOREST', atk: 1, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [2], ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    rotateTargetOnDamage: { mode: 'OPPOSITE' },
    desc: 'When Archeress damages (but does not destroy) a creature, that creature is rotated 180° and cannot counterattack.'
  },

  FOREST_ELVEN_BERSERKER_MAIDEN: {
    cardNumber: 59,
    race: 'Elf',
    affiliation: 'Black Forest',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_ELVEN_BERSERKER_MAIDEN', name: 'Elven Berserker Maiden', type: 'UNIT', cost: 2, activation: 1,
    element: 'FOREST', atk: 1, hp: 3,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreAlliedBlocking: true } ],
    blindspots: ['S'],
    ignoreAlliedBlocking: true,
    hpEqualsBonuses: [ { hp: 1, atk: 2, dodgeAttempts: 1, dodgeChance: 0.5 } ],
    desc: 'While Elven Berserker Maiden has exactly 1 HP, she adds 2 to her Attack and gains a Dodge attempt.'
  },

  FOREST_GREEN_CUBIC: {
    cardNumber: 72,
    race: 'Egg',
    affiliation: 'Unknown',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_GREEN_CUBIC', name: 'Green Cubic', type: 'UNIT', cost: 1, activation: 1,
    element: 'FOREST', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['E', 'S', 'W'],
    unitActions: [
      { key: 'SACRIFICE_TRANSFORM', element: 'FOREST', label: 'Sacrifice', requireNonCubic: true, allowLockedTargets: true },
    ],
    desc: 'Sacrifice Green Cubic to summon a non‑cubic Wood creature in its place (facing any direction) without paying the summoning cost. The summoned creature cannot attack on this turn.'
  },
  FOREST_GREEN_ERLKING_ZOMBA: {
    cardNumber: 70,
    race: 'Noble',
    affiliation: 'Green Bandits',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'FOREST_GREEN_ERLKING_ZOMBA', name: 'Green Erlking Zomba', type: 'UNIT', cost: 6, activation: 3,
    element: 'FOREST', atk: 6, hp: 3,
    attackType: 'STANDARD', friendlyFire: true,
    attacks: [ { dir: 'N', ranges: [1, 2], ignoreAlliedBlocking: true } ],
    attackSchemes: [
      { key: 'BASE', label: 'Base', attackType: 'STANDARD', attacks: [ { dir: 'N', ranges: [1, 2], ignoreAlliedBlocking: true } ] },
      { key: 'ALT', label: 'Wood', attackType: 'STANDARD', attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ] }
    ],
    defaultAttackScheme: 'BASE',
    mustUseSchemeOnElement: { element: 'FOREST', scheme: 'ALT' },
    blindspots: ['S'], ignoreAlliedBlocking: true, pierce: true,
    allyDeathDiscardOnElement: { element: 'FOREST', amount: 1 },
    desc: 'Zomba must use its secondary attack while it is on a Wood field. While Zomba is on a Wood field, each time an allied creature is destroyed, your opponent must discard a card.'
  },
  FOREST_LEAPFROG_BANDIT: {
    cardNumber: 55,
    race: 'Anthromorph',
    affiliation: 'Green Bandits',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_LEAPFROG_BANDIT', name: 'Leapfrog Bandit', type: 'UNIT', cost: 1, activation: 1,
    element: 'FOREST', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [2], ignoreBlocking: true, ignoreAlliedBlocking: true } ],
    blindspots: ['S'], ignoreAlliedBlocking: true,
    deathDiscardOnNonElement: { element: 'FOREST', count: 1 },
    desc: 'If Leapfrog Bandit is destroyed on a non-Wood field, your opponent must discard 1 card.'
  },
  SAMURAI_NAGIRASHU: {
    cardNumber: 60,
    race: 'Human',
    affiliation: 'Nagirashu',
    fieldLock: false,
    cardLimit: null,
    id: 'SAMURAI_NAGIRASHU', name: 'Samurai Nagirashu', type: 'UNIT', cost: 2, activation: 2,
    element: 'FOREST', atk: 2, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1], ignoreAlliedBlocking: true } ],
    blindspots: ['S'], ignoreAlliedBlocking: true,
    deathDiscardOnElement: { element: 'FOREST', count: 1 },
    desc: 'If Samurai Nagirashu is destroyed on a Wood field, your opponent must discard 1 card.'
  },
  NEUTRAL_WHITE_CUBIC: {
    cardNumber: 90,
    race: 'Egg',
    affiliation: 'Unknown',
    fieldLock: false,
    cardLimit: { type: 'PER_CARD', amount: 1 },
    id: 'NEUTRAL_WHITE_CUBIC', name: 'White Cubic', type: 'UNIT', cost: 1, activation: 1,
    element: 'NEUTRAL', atk: 1, hp: 1,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['E', 'S', 'W'],
    keywords: ['DODGE_ATTEMPT'],
    dodge: { chance: 0.5, attempts: 1 },
    unitActions: [
      { key: 'SACRIFICE_TRANSFORM', label: 'Sacrifice', allowAnyElement: true, requireNonCubic: false, allowLockedTargets: true },
    ],
    desc: 'White Cubic does not belong to any element. Sacrifice White Cubic to summon any creature in its place (facing any direction) without paying the Summoning Cost. The summoned creature cannot attack this turn. Dodge attempt.'
  },

  BIOLITH_NINJA: {
    cardNumber: 78,
    race: 'Mech',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_NINJA', name: 'Biolith Ninja', type: 'UNIT', cost: 4, activation: 2,
    element: 'BIOLITH', atk: 4, hp: 2,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    backAttack: true,
    gainPerfectDodgeOnElement: 'BIOLITH',
    desc: 'While on a Biolith field it gains Perfect Dodge. Always attacks the back of its target.'
  },

  BIOLITH_BOMBER: {
    cardNumber: 73,
    race: 'Blitz',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_BOMBER', name: 'Biolith Bomber', type: 'UNIT', cost: 3, activation: 2,
    element: 'BIOLITH', atk: 1, hp: 3,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1, 2], mode: 'ANY', ignoreBlocking: true },
      { dir: 'E', ranges: [1, 2], mode: 'ANY', ignoreBlocking: true },
      { dir: 'S', ranges: [1, 2], mode: 'ANY', ignoreBlocking: true },
      { dir: 'W', ranges: [1, 2], mode: 'ANY', ignoreBlocking: true },
    ],
    blindspots: ['S'],
    plusAtkVsSummonCostAtMost: { limit: 2, amount: 2 },
    desc: 'Adds 2 to its Attack if the target creature has a Summoning Cost of 2 or lower.'
  },
  BIOLITH_SCION_BIOLITH_LORD: {
    cardNumber: 87,
    race: 'Noble',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: { type: 'PER_RACE', amount: 1 },
    id: 'BIOLITH_SCION_BIOLITH_LORD', name: 'Scion, Biolith Lord', type: 'UNIT', cost: 6, activation: 3,
    element: 'BIOLITH', atk: 2, hp: 5,
    attackType: 'MAGIC',
    attacks: [],
    blindspots: ['N', 'E', 'S', 'W'],
    magicTargetsSameElement: true,
    auraModifiers: [
      { stat: 'ACTIVATION', amount: -2, target: 'ALLY', scope: 'BOARD', targetElement: 'BIOLITH', excludeSelf: true },
    ],
    desc: 'Scion\'s Magic Attack targets all enemies of the same element as the target. All other allied Biolith creatures subtract 2 from their Activation Cost.'
  },
  BIOLITH_DRAGOON_DRAGON_CAVALRY: {
    cardNumber: 80,
    race: 'Mech',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_DRAGOON_DRAGON_CAVALRY', name: 'Dragoon Dragon Cavalry', type: 'UNIT', cost: 5, activation: 3,
    element: 'BIOLITH', atk: 3, hp: 5,
    attackType: 'STANDARD',
    attacks: [ { dir: 'N', ranges: [1] } ],
    blindspots: ['S'],
    doubleAttack: true,
    desc: 'Dragoon Dragon Cavalry attacks the same target twice. The counterattack of target creature occurs after the second attack. All enemy dragons subtract 3 from their Attack.'
  },

  BIOLITH_BATTLE_CHARIOT: {
    cardNumber: 76,
    race: 'Weapon',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_BATTLE_CHARIOT', name: 'Biolith Battle Chariot', type: 'UNIT', cost: 4, activation: 4,
    element: 'BIOLITH', atk: 3, hp: 5,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1], group: 'FRONT_RIGHT' },
      { dir: 'E', ranges: [1], group: 'FRONT_RIGHT' },
    ],
    friendlyFire: true,
    blindspots: ['S'],
    desc: ''
  },

  BIOLITH_AEGIS_CITADEL: {
    cardNumber: 82,
    race: 'Base',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_AEGIS_CITADEL', name: 'Aegis Citadel', type: 'UNIT', cost: 5, activation: 3,
    element: 'BIOLITH', atk: 1, hp: 5,
    attackType: 'STANDARD', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'E', ranges: [1] },
      { dir: 'S', ranges: [1] },
      { dir: 'W', ranges: [1] }
    ],
    blindspots: [],
    fortress: true,
    invisibilityAuraSameElement: true,
    desc: 'Fortress: cannot attack except when counterattacking. Grants Invisibility to all allied creatures of the same element as the field it occupies.'
  },

  BIOLITH_TAURUS_MONOLITH: {
    cardNumber: 81,
    race: 'Titan',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_TAURUS_MONOLITH', name: 'Taurus Monolith', type: 'UNIT', cost: 5, activation: 3,
    element: 'BIOLITH', atk: 3, hp: 6,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1], group: 'DOUBLE_FRONT', ignoreBlocking: true },
      { dir: 'N', ranges: [2], group: 'DOUBLE_FRONT', ignoreBlocking: true },
    ],
    blindspots: ['S'],
    pushTargetOnDamage: { distance: 1 },
    desc: 'If Taurus Monolith attacks (but does not destroy) a creature, that creature is pushed back one field in the direction of the attack (provided the field is empty) and cannot counterattack.'
  },

  BIOLITH_ARC_SATELLITE_CANNON: {
    cardNumber: 83,
    race: 'Blitz',
    affiliation: 'Biolith Castle',
    fieldLock: true,
    locked: true,
    cardLimit: null,
    id: 'BIOLITH_ARC_SATELLITE_CANNON', name: 'Arc Satellite Cannon', type: 'UNIT', cost: 5, activation: 4,
    element: 'BIOLITH', atk: 4, hp: 5,
    attackType: 'MAGIC', chooseDir: true,
    attacks: [
      { dir: 'N', ranges: [1, 2], mode: 'ANY' },
      { dir: 'E', ranges: [1, 2], mode: 'ANY' },
      { dir: 'S', ranges: [1, 2], mode: 'ANY' },
      { dir: 'W', ranges: [1, 2], mode: 'ANY' },
    ],
    blindspots: ['S'],
    desc: 'Magic Attack: choose one highlighted cell in front, back, left or right to target.'
  },

  FOREST_TWIN_GOBLINS: {
    cardNumber: 61,
    race: 'Goblin',
    affiliation: 'Green Bandits',
    fieldLock: false,
    cardLimit: null,
    id: 'FOREST_TWIN_GOBLINS', name: 'Twin Goblins', type: 'UNIT', cost: 2, activation: 1,
    element: 'FOREST', atk: 1, hp: 3,
    attackType: 'STANDARD',
    attacks: [
      { dir: 'N', ranges: [1] },
      { dir: 'S', ranges: [1] },
    ],
    blindspots: [],
    friendlyFire: true,
    desc: ''
  },

  // Spells (subset)
  SPELL_HEALING_SHOWER: {
    cardNumber: 97,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_HEALING_SHOWER',
    name: 'Healing Shower',
    type: 'SPELL',
    element: 'EARTH',
    spellType: 'CONJURATION',
    cost: 2,
    text: 'All allied creatures of a chosen element gain 3 HP. Place this card on an allied creature belonging to the desired element.'
  },
  SPELL_FISSURES_OF_GOGHLIE: {
    cardNumber: 98,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_FISSURES_OF_GOGHLIE',
    name: 'Fissures of Goghlie',
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'CONJURATION',
    cost: 2,
    text: 'Fieldquake any one field.'
  },
  SPELL_GREAT_TOLICORE_QUAKE: {
    cardNumber: 99,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_GREAT_TOLICORE_QUAKE',
    name: 'Great Tolicore Quake',
    type: 'SPELL',
    element: 'BIOLITH',
    spellType: 'CONJURATION',
    cost: 4,
    text: 'Fieldquake all fields of a chosen element. Place this card on a field of the chosen element.'
  },
  SPELL_PARMTETIC_HOLY_FEAST: {
    cardNumber: 91,
    race: 'Ritual',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_CARD', amount: 1 },
    id: 'SPELL_PARMTETIC_HOLY_FEAST',
    name: 'Parmetic Holy Feast',
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'RITUAL',
    cost: 0,
    ritualCost: 'discard 1 creature',
    text: 'Discard a creature from hand and gain 2 mana.'
  },
  SPELL_GOGHLIE_ALTAR: {
    cardNumber: 92,
    race: 'Ritual',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_CARD', amount: 1 },
    id: 'SPELL_GOGHLIE_ALTAR',
    name: 'Goghlie Altar',
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'RITUAL',
    cost: 0,
    ritualCost: 'none',
    text: 'Both players gain mana equal to the number of enemy creatures on the board.'
  },
  SPELL_SUMMONER_MESMERS_LAPSE: {
    cardNumber: 93,
    race: 'Ritual',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: { type: 'PER_CARD', amount: 1 },
    id: 'SPELL_SUMMONER_MESMERS_LAPSE',
    name: "Summoner Mesmer's Lapse",
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'RITUAL',
    cost: 0,
    ritualCost: 'discard 1 creature',
    text: 'Discard a creature from hand. Opponent loses mana equal to its summoning cost.'
  },
  SPELL_BEGUILING_FOG: {
    cardNumber: 94,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_BEGUILING_FOG',
    name: 'Beguiling Fog',
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'CONJURATION',
    cost: 0,
    text: 'Rotate any one creature in any direction.'
  },
  SPELL_YUGAS_MESMERIZING_FOG: {
    cardNumber: 95,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_YUGAS_MESMERIZING_FOG',
    name: "Yuga's Mesmerizing Fog",
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'CONJURATION',
    cost: 1,
    text: 'Choose an allied creature. All adjacent enemies rotate so their backs face that creature.'
  },
  SPELL_CLARE_WILS_BANNER: {
    cardNumber: 96,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_CLARE_WILS_BANNER',
    name: 'Clare Wil’s Banner',
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'CONJURATION',
    cost: 1,
    text: 'Friendly creatures get +1 ATK until end of turn.'
  },
  SPELL_SUMMONER_MESMERS_ERRAND: {
    cardNumber: 100,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_SUMMONER_MESMERS_ERRAND',
    name: "Summoner Mesmer's Errand",
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'CONJURATION',
    cost: 1,
    text: 'Draw two cards.'
  },
  SPELL_TINOAN_TELEKINESIS: {
    cardNumber: 101,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_TINOAN_TELEKINESIS',
    name: 'Tinoan Telekinesis',
    type: 'SPELL',
    element: 'BIOLITH',
    spellType: 'CONJURATION',
    cost: 2,
    text: 'Move 1 allied creature to an empty field without changing its orientation. Place this card over the target creature, then select an empty field.'
  },
  SPELL_TINOAN_TELEPORTATION: {
    cardNumber: 102,
    race: 'Conjuration',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_TINOAN_TELEPORTATION',
    name: 'Tinoan Teleportation',
    type: 'SPELL',
    element: 'BIOLITH',
    spellType: 'CONJURATION',
    cost: 3,
    text: 'Switch the locations of two allied creatures without changing their orientations. Place this card over the 1st target, then the 2nd target.'
  },
  SPELL_SEER_VIZAKS_CALAMITY: {
    cardNumber: 109,
    race: 'Sorcery',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_SEER_VIZAKS_CALAMITY',
    name: "Seer Vizak's Calamity",
    type: 'SPELL',
    element: 'BIOLITH',
    spellType: 'SORCERY',
    cost: 5,
    text: 'Fieldquake all fields. Playing this card ends your turn. Offer this card to the Eye.'
  },
  SPELL_CALL_OF_TIMELESS_JUNO: {
    cardNumber: 110,
    race: 'Sorcery',
    affiliation: 'None',
    fieldLock: false,
    cardLimit: null,
    id: 'SPELL_CALL_OF_TIMELESS_JUNO',
    name: 'Call of Timeless Juno',
    type: 'SPELL',
    element: 'NEUTRAL',
    spellType: 'SORCERY',
    cost: 5,
    text: 'Select two fields to exchange their elements. Creatures stay in place. Playing this card ends your turn.'
  },
};

export const CARDS = Object.fromEntries(
  Object.entries(RAW_CARDS).map(([id, card]) => [id, { ...card }])
);
