// Определение доступных колод
// Каждая колода включает id, имя, описание и список карт

import { STARTER_FIRESET, CARDS } from './cards.js';

// Вариант со слегка изменённым набором
const BALANCED_BLAZE = [
  CARDS.FIRE_FLAME_MAGUS,
  CARDS.FIRE_HELLFIRE_SPITTER,
  CARDS.FIRE_FREEDONIAN,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_GREAT_MINOS,
  CARDS.FIRE_FLAME_ASCETIC,
  CARDS.FIRE_TRICEPTAUR,
  CARDS.FIRE_PURSUER,
  CARDS.FIRE_HELLFIRE_SPITTER,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_FLAME_ASCETIC,
  CARDS.FIRE_PURSUER,
  CARDS.RAISE_STONE,
  CARDS.RAISE_STONE,
  CARDS.SPELL_PARMTETIC_HOLY_FEAST,
  CARDS.SPELL_SUMMONER_MESMERS_ERRAND,
  CARDS.SPELL_GOGHLIE_ALTAR,
  CARDS.SPELL_CLARE_WILS_BANNER,
  CARDS.SPELL_BEGUILING_FOG,
  CARDS.SPELL_FISSURES_OF_GOGHLIE,
].filter(Boolean);

// Колода только из существ
const CREATURE_SWARM = [
  CARDS.FIRE_FLAME_MAGUS,
  CARDS.FIRE_HELLFIRE_SPITTER,
  CARDS.FIRE_FREEDONIAN,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_GREAT_MINOS,
  CARDS.FIRE_FLAME_ASCETIC,
  CARDS.FIRE_TRICEPTAUR,
  CARDS.FIRE_PURSUER,
  CARDS.FIRE_FLAME_MAGUS,
  CARDS.FIRE_HELLFIRE_SPITTER,
  CARDS.FIRE_FREEDONIAN,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_GREAT_MINOS,
  CARDS.FIRE_FLAME_ASCETIC,
  CARDS.FIRE_TRICEPTAUR,
  CARDS.FIRE_PURSUER,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_FLAME_ASCETIC,
  CARDS.FIRE_TRICEPTAUR,
  CARDS.FIRE_PURSUER,
].filter(Boolean);

// Экспериментальная смесь для проверки
const EXPERIMENT_MIX = [
  CARDS.FIRE_FLAME_MAGUS,
  CARDS.FIRE_FLAME_MAGUS,
  CARDS.FIRE_HELLFIRE_SPITTER,
  CARDS.FIRE_HELLFIRE_SPITTER,
  CARDS.FIRE_FREEDONIAN,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_FLAME_LIZARD,
  CARDS.FIRE_GREAT_MINOS,
  CARDS.FIRE_FLAME_ASCETIC,
  CARDS.FIRE_TRICEPTAUR,
  CARDS.FIRE_PURSUER,
  CARDS.SPELL_PARMTETIC_HOLY_FEAST,
  CARDS.SPELL_PARMTETIC_HOLY_FEAST,
  CARDS.SPELL_GOGHLIE_ALTAR,
  CARDS.SPELL_GOGHLIE_ALTAR,
  CARDS.SPELL_CLARE_WILS_BANNER,
  CARDS.SPELL_SUMMONER_MESMERS_ERRAND,
  CARDS.SPELL_SUMMONER_MESMERS_ERRAND,
  CARDS.SPELL_FISSURES_OF_GOGHLIE,
  CARDS.SPELL_BEGUILING_FOG,
].filter(Boolean);

export const DECKS = [
  {
    id: 'FIRE_STARTER',
    name: 'Flame Awakening',
    description: 'A basic set of fiery spells and creatures.',
    cards: STARTER_FIRESET,
  },
  {
    id: 'BALANCED_BLAZE',
    name: 'Balanced Blaze',
    description: 'A versatile mix of units and spells.',
    cards: BALANCED_BLAZE,
  },
  {
    id: 'CREATURE_SWARM',
    name: 'Creature Swarm',
    description: 'All creatures, no spells.',
    cards: CREATURE_SWARM,
  },
  {
    id: 'EXPERIMENT_MIX',
    name: 'Experimental Mix',
    description: 'Prototype deck packed with odd tools.',
    cards: EXPERIMENT_MIX,
  },
];

const api = { DECKS };
try { if (typeof window !== 'undefined') { window.DECKS = DECKS; } } catch {}
export default api;
